### ISSUE TITLE
Useless ModelDefinition.type

### ISSUE THREAD

**Issue by ylussaud** [ObeoNetwork/M2Doc#122]
It seems useless and error prone to have to set the type of the ModelDefinition since the value itself reference ifs types.

My guess is we should get rid of it.

**Comment by cbrun** [comment]
In my understanding the rationale is to populate this "type" reference based when analysing the .docx template or "by hand" so that the user can *then* select the right instances without being overwhelmed by thousands of those which are not relevant.  Yes, once the value is set it is useless, but it is used to make it convenient to set the value.

I guess this can be removed once the UI widgets are usable with such big models.

**Comment by ylussaud** [comment]
OK I get it... So we might want to keep it. I'm closing this issue
