### ISSUE TITLE
Maximum size of 255 char for fields may be a problem for the list of nsURIs to use.

### ISSUE THREAD

**Issue by flatombe** [ObeoNetwork/M2Doc#198]
The metamodel nsURIs used by variables available in the template are stored in a field "m:uri". However, fields have a maximum size of 255 characters. In practice, considering the typical length of nsURIS, this limits us to the use of 5-10 metamodels.

**Comment by ylussaud** [comment]
In order to fix that I'll change template custom properties as follow:

m:var: is unchanged
m:uri becomes m:uri:<EPackage nsURI> (EPackage nsURI in key not as value)
m:services becomes m:services:<Token> (Token in key not as value)
m:import becomes m:import:<qualified class name> (qualified class name in key not as value)

Unfortunately it will break existing templates. A manual migration will be needed.
