### ISSUE TITLE
M2Doc syntax relies partially on blank spaces

### ISSUE THREAD

**Issue by flatombe** [ObeoNetwork/M2Doc#241]
In a template, the following syntaxes fail due to the blank space:

- `{m: if ...}`: <---Expression "if ..." is invalid: incomplet conditional

- `{m: for ...}`: <---Couldn't find the 'for' variable

The fix is to remove the blank space:

- `{m:if ...}`

- `{m:for ...}`

At the very least, the error should mention the extraneous blank space. Ideally, the syntax should not be sensible to white spaces.

**Comment by ylussaud** [comment]
m: is used for AQL expression and "m: if condition then a else b endif" is a valid AQL expression. That's why the space after ":" is not supporter be M2Doc. And a variable can be named for in AQL, may not be the best idea but it's legal.

But it's clearly a problem since MS Word has the tendency to automatically add spaces... I'll add an explicit information message in this case to limit trouble shooting.
