### ISSUE TITLE
Required support for UML2 and SysML models

### ISSUE THREAD

**Issue by hbalp** [ObeoNetwork/M2Doc#269]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please have a look to the support pages of our website : http://m2doc.org/support/
</code></pre>

## Current behavior

As for GenDoc, it would be nice if M2Doc would support UML2 and SysML models.
Currently, when I try to use M2Doc with a simple UML model named HelloWorld containing one package Hello, itself containg a package World, an error is raised when validating the genconf script and the error is reported as follows:

![helloworld uml2 m2doc validation-error](https://user-images.githubusercontent.com/11596356/32751148-12005184-c8c5-11e7-9439-79d5fe3af8f9.png)

I can avoid this validation error by adding oclAsType as follows: 
 **{m:self.oclAsType(uml!Package).packagedElement.name}**

However, even if the .genconf script is now well validated by M2Doc and a .docx document is generated, the content of the generated file is incorrect. It includes an error reported at runtime with its complete stack trace, as follows:

![helloworld uml2 m2doc generation-error](https://user-images.githubusercontent.com/11596356/32751866-7c1fdf1a-c8c7-11e7-8a17-ccd1bfa4509e.png)

## Expected behavior

I would have expect an automatic recognition by M2Doc of the UML2 types referenced by the model and a correct resolution of the M2Doc instruction **{m:self.packagedElement.name}**, so as any other aql query compliant with the UML2 metamodel.

The generated document should simply dump the names of the HelloWorld model so as the Hello UML subpackage.

## Minimal reproduction of the problem with instructions

The joined archive includes the helloWorld test with the two .genconf files mentioned above (one with .oclAsType and the other without) so as the resulting .docx files reporting the two kinds of errors.

This example has been tested on Windows 10, with jdk-1.8,
ObeoDesigner-9.1 and UML Designer 7.1.0.201611...

## What is the motivation / use case for changing the behavior?

M2Doc is useless for generating Word documentation from UML2 or SysML models without such required support.

## Environment

<pre><code>
M2Doc version: 1.0.0.20170121
Eclipse version: ObeoDesigner-9.1.2.20170908
Platform version:  Windows 10

Others:
UML Designer 7.1.0.201611
SysML Designer 7.1.0.201611
</code></pre>
[helloWorld.uml2.m2doc.test.zip](https://github.com/ObeoNetwork/M2Doc/files/1468854/helloWorld.uml2.m2doc.test.zip)

**Comment by ylussaud** [comment]
I think uml/sysml should work out of the box.
You have some problems with your template:

First the validation error suggest you have declared your self variable as an ecore::EPackage and not a uml::Model. You can change this using the [template editor](http://www.m2doc.org/ref-doc/nightly/index.html#template-editor) or [MS word](http://www.m2doc.org/ref-doc/nightly/index.html#template-custom-properties). To be abble to sleect the uml::Model type you also need to add UML2 to your EPackage nsURIs.

Also the expression should be:

{m:self.oclAsType(um::Package).packagedElement.name}

note the '::' instead of the '!'. After correcting the variable type the 'oclAsType' call should not be needed anymore.

**Comment by ylussaud** [comment]
We need to add tests on UML2 models
