### ISSUE TITLE
Extract diagrams and data with M2DOC

### ISSUE THREAD

**Issue by NoPainNoGain9** [ObeoNetwork/M2Doc#276]
Hi all,

In Capella 1.1.1 with M2DOC 1.0.0, I’m looking for a smart way to export diagrams related to a Logical Component, AND extract data from it in a table.

For example, in Logical Architecture, I have a Logical Component with 5 related diagrams which contain multiple different objects (Logical Components, Functions…). On these diagrams are also displayed different Functional Chains.
  
My aim is to export a WORD document with these 5 pictures and, under each of them, a table which shows title and description of Functional Chain currently displayed. Obviously, there are several Logical Components which need the same operation in my model.

I previously achieved this operation with M2DOC 0.9 by creating a Variable whose value was DAnalysis
and exploring it with “.eAllContents(diagram::DSemanticDiagram)” plus several condition “if” applied on the name of the diagrams. However, it seems to not work anymore (error message in template) :(

With M2DOC 1.0.0 syntax/code, what is the best way to do it ? 

Thanks for your help

**Comment by ylussaud** [comment]
You probably want to use [Sirius services](http://www.m2doc.org/ref-doc/nightly/m2doc_service_m2docsiriusservices.html).

What is the error message ?

**Comment by NoPainNoGain9** [comment]
{ m:let picture **<---Empty collection: Nothing can be left after calling eAllContents: EClassifier=Danalysis can't contain EClassifierLiteral=DSemanticDiagram directly or indirectly** = source.eAllContents(diagram::DSemanticDiagram) }
...
{ m:endlet }

My variable type is:

source: viewpoint::Danalysis

**Comment by ylussaud** [comment]
This might be related to a change in the Sirius metamodels. Now there is an indirection using DRepresentationDescriptor in order to lazy load DRepresentation.
You can probably use something like this:

source.eAllContents(viewpoint::RepresentationDescription).representation->filter(diagram::DSemanticDiagram)

But this will laod all representations... An other way of doing this if you know or can compute the representation name is

'representation name'.asImage()

You need to set the SiriusSession option in the .genconf file to the corresponding .aird file. There is examples of this service [here](https://github.com/ObeoNetwork/M2Doc/tree/master/tests/org.obeonetwork.m2doc.sirius.tests/resources/m2DocSiriusServices/asImageByRepresentationName).

**Comment by NoPainNoGain9** [comment]
It works ! type is viewpoint::DRepresentationDescriptor
Thanks !
