### ISSUE TITLE
Bug Report - Function eInverse creates Error Message

### ISSUE THREAD

**Issue by looc13** [ObeoNetwork/M2Doc#285]
I wanted to use the function "eInverse".
In the Interpreter the function works.
![m2doc_2](https://user-images.githubusercontent.com/37613240/37698761-a642068e-2ce4-11e8-81a4-0eaac0517ac6.jpg)

But if I put the same function into a M2Doc Template there comes this error.
The error does also appear when i use function without a parameter.
![m2doc_1](https://user-images.githubusercontent.com/37613240/37698898-499b2630-2ce5-11e8-93ee-9800c2f24d47.jpg)

M2Doc version: 1.1.0.201801251029
Capella 1.2.0
Platform version:  Windows 7, Microsoft Office 365 Version 1708

**Comment by ylussaud** [comment]
In order to use the eInverse() service you need to create an environment with a CrossReferenceProvider. see:
org.eclipse.acceleo.query.runtime.Query.newEnvironmentWithDefaultServices()

M2Doc don't provide one by default because of the scope of cross references that can only be decided by the user and also it can be expensive in time to install a cross referencer. But you can change that programmatically by providing your own IReadOnlyQueryEnvironment to M2DocUtils.generate(...).

**Comment by looc13** [comment]
Thank you for the fast response. 
Where I can find a description how to create an enviroment with a CrossReferenceProvider?

**Comment by ylussaud** [comment]
You need to do it programmatically:

CrossReferencer xRef = new CrossReferencer(rootEObject);
CrossReferencerToAQL crossReferencer = new CrossReferencerToAQL(xRef);
IQueryEnvironment env = org.eclipse.acceleo.query.runtime.Query.newEnvironmentWithDefaultServices(crossReferencer);

See GenconfUtils.getQueryEnvironment() for more context or if you want to generate from a Generation.
