### ISSUE TITLE
Hyperlinks from sub-templates still does not work

### ISSUE THREAD

**Issue by dsryzhov** [ObeoNetwork/M2Doc#354]
Hyperlinks from sub-templates still does not work

When several hyperlinks are created in sub-template all urls are equal to the last one. 

When sub-template with several hyperlinks creation is called from loop all hyperlinks urls are empty except the last one. 

Result docx file is corrupted but can be opened after confirmation.

Attached to this issue are test template and generated document that shows this behaviour. 
![2019-06-11 14_29_29-Template](https://user-images.githubusercontent.com/46596843/59268487-74ba8380-8c55-11e9-94c5-8a79d27e559c.png)

![generated](https://user-images.githubusercontent.com/46596843/59268616-c6fba480-8c55-11e9-8990-2141e220428b.png)

[Template.docx](https://github.com/ObeoNetwork/M2Doc/files/3276267/Template.docx)

[generated.docx](https://github.com/ObeoNetwork/M2Doc/files/3276270/generated.docx)

**Comment by ylussaud** [comment]
Yes I think my test produced a special case when the hyperlink was copied but in the general case it doesn't happen. There is no representation of hyperlink at the XWPF* level of POI A§PI. To copy it we need to go to the XML level with CT*, in order to do this we need to change the parsing and the AST in M2Doc... and of course the generation engine. Doing this will also solve issues with bookmark.

I'll reopen #348 and close this one as a duplicate.
