### ISSUE TITLE
Table and Figures references are removed by M2Doc when UpdateFields option is set to true

### ISSUE THREAD

**Issue by ylussaud** [ObeoNetwork/M2Doc#412]
Table and Figures references are removed by M2Doc when UpdateFields option is set to true.

**Comment by ylussaud** [comment]
In some case a static bookmark is destroyed by M2Doc see bug #415.
This bug should focus on Tables and Figure references.

**Comment by jaspfl** [comment]
The issue does appear when using Word 2016 but not when using Word 2010.

I attached 4 documents. 2 templates and 2 generated documents. The templates were configured for capella 1.4.2 and M2Doc 3.2.0. The only m2doc field is `self.name`.

When opening the generated documents, one can immediately see that the 2016 version is missing the number highlighting that 2010 has. When refreshing all fields in the document (CTRL+A, F9), nothing changes for 2010 but the ToC in 2016 shows that there are no links to depict. The generated files were not altered after generation in order to have this demonstration handy 

[Example Word2010.docx](https://github.com/ObeoNetwork/M2Doc/files/7897003/Example.Word2010.docx)
[Example Word2010.generated.docx](https://github.com/ObeoNetwork/M2Doc/files/7897004/Example.Word2010.generated.docx)
[Example Word2016.docx](https://github.com/ObeoNetwork/M2Doc/files/7897005/Example.Word2016.docx)
[Example Word2016.generated.docx](https://github.com/ObeoNetwork/M2Doc/files/7897006/Example.Word2016.generated.docx)

**Comment by ylussaud** [comment]
More details in this [discussion](https://forum.mbse-capella.org/t/word-captions-removed-by-m2doc/4999).

**Comment by e-shreve-ti** [comment]
A workaround is to use the m2doc template field to wrap the SEQ field:
```
{ m:template makeTableRef(s : String) }{m:s} { SEQ Table \* ARABIC }{ m:endtemplate}
Example Use
{ m:'Table'.makeTableRef() } - Referenced Documents
```
